name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: Projet-technique-Altair/altair-ci/.github/workflows/gke-microservice-cd.yml@main
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      artifact_registry_host: ${{ vars.GCP_ARTIFACT_REGISTRY_HOST }}
      artifact_registry_repo: ${{ vars.GCP_ARTIFACT_REPO }}
      workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
      deploy_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      gke_cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
      gke_cluster_location: ${{ vars.GKE_CLUSTER_LOCATION }}

      image_name: altair-proxy-lab-web
      k8s_namespace: ${{ vars.K8S_NAMESPACE }}
      k8s_deployment_name: ${{ vars.K8S_DEPLOYMENT_NAME }}
      k8s_container_name: altair-proxy-lab-web

      workdir: .
      dockerfile: Dockerfile
      platform: linux/amd64
      manifest_path: k8s/deployment.yaml
