name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag de l'image a redeployer manuellement (sha ou vN)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    uses: Projet-technique-Altair/altair-ci/.github/workflows/gke-microservice-cd.yml@main
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      artifact_registry_host: ${{ vars.GCP_ARTIFACT_REGISTRY_HOST }}
      artifact_registry_repo: ${{ vars.GCP_ARTIFACT_REPO }}
      workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
      deploy_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      gke_cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
      gke_cluster_location: ${{ vars.GKE_CLUSTER_LOCATION }}

      image_name: altair-proxy-lab-web
      image_tag: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || '' }}
      k8s_namespace: ${{ vars.K8S_NAMESPACE }}
      k8s_deployment_name: ${{ vars.K8S_DEPLOYMENT_NAME }}
      k8s_container_name: altair-proxy-lab-web
      manifest_path: k8s/deployment.yaml
